In [ ]:
"""  Different ways to creating dataframe,

Topics Covered

1. Using CSV
2. Using Excel
3. From python dictionary
4. From list of tuples
5. From list of dictionaries
"""

In [4]:
import pandas as pd

######################### 
# create DF using csv file
######################### 

df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/pandas/3_different_ways_of_creating_dataframe/weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [5]:
######################### 
# create DF using xlsx file
######################### 

# df = pd.read_excel('<xlsx file path>', '<sheetname>')

In [7]:
######################### 
# create DF using python dictionary
######################### 
weather_data = {
    'day': ['1/1/2020', '1/2/2020', '1/3/2020', '1/4/2020'],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow'],
    'windspeed': [6,7,2,7],
    'temperature': [32,35,28,24]
}

df = pd.DataFrame(weather_data)
df

        day  event  windspeed  temperature
0  1/1/2020   Rain          6           32
1  1/2/2020  Sunny          7           35
2  1/3/2020   Snow          2           28
3  1/4/2020   Snow          7           24

In [8]:
######################### 
# create DF using list of tuples
#########################
weather_data = [
    ('1/1/2020', 32, 6, 'Rain'),
    ('1/2/2020', 35, 7, 'Sunny'),
    ('1/3/2020', 28, 2, 'Snow'),
]
df = pd.DataFrame(weather_data, columns=['day', 'temperature', 'windspeed', 'event'])
df

        day  temperature  windspeed  event
0  1/1/2020           32          6   Rain
1  1/2/2020           35          7  Sunny
2  1/3/2020           28          2   Snow

In [9]:
######################### 
# create DF using list of dictionary
######################### 
weather_data = [
    {'day': '1/1/2020', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/1/2020', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/1/2020', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
]

df = pd.DataFrame(weather_data)
df

        day  event  temperature  windspeed
0  1/1/2020   Rain           32          6
1  1/1/2020  Sunny           35          7
2  1/1/2020   Snow           28          2